wandb : False
cuda : True
csv_file_path : "data/face_landmarks.csv"
root_dir : "data/images/"
train: False
predict : False
model_name : "Baseline"
model_gen : 1


#train
epochs : nul
verbose : nul
lr : nul
batch_size : 4
evaluate_every : False
save_model : False
save_every : False
num_workers : 1

#predict
model_dir : nul
save_figures_path : nul


