
# train_default.yaml
train: True
wandb : False
epochs : 1
verbose : False
cuda : True
lr : 0.001
batch_size : 50
csv_file_path : "data/face_landmarks.csv"
root_dir : "data/images/"
evaluate_every : 1
save_model : True
save_every : False  
num_workers : 1
predict : False

